name: alclock
description: Sleep Tracking + Smart Alarm mobile app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Localization
  flutter_localizations:
    sdk: flutter

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Networking
  dio: ^5.4.0

  # UI
  fl_chart: ^0.66.0
  intl: ^0.20.2
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  workmanager: ^0.5.2
  screen_brightness: ^0.2.2+1
  wakelock_plus: ^1.2.1

  # Utils
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.0
  
  # Audio
  just_audio: ^0.9.36

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  riverpod_generator: ^2.3.9
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/quotes/islamic_quotes.json
    - assets/sounds/
  
  # Localization
  generate: true
   
